In [130]:
import matplotlib.pyplot as plt
import numpy as np
from hlsf.models import *
from scipy.interpolate import RectBivariateSpline
%matplotlib qt

In [131]:
config = 'H'
lamp = 'Kr'

In [132]:
lsf_data = LSF_DATA(f"../exposures/ARC-{lamp}_CLEAR_20MAS_{config}_PRM.fits", f"../text/{lamp}.txt", f"../exposures/WAVECAL_TABLE_20MAS_{config}.fits", 
                        f"../exposures/SLITLET_TABLE_20MAS_{config}.fits")
lsf_data.get_line_list()

{171: 14402.22,
 172: 14426.793,
 173: 14517.84,
 174: 14734.436,
 177: 14961.894,
 178: 15005.307,
 179: 15209.526,
 180: 15239.615,
 181: 15326.48,
 182: 15334.958,
 183: 15372.037,
 184: 15474.026,
 185: 15681.02,
 186: 15820.09,
 187: 16726.513,
 188: 16785.128,
 189: 16853.488,
 192: 16935.806,
 193: 17098.771,
 194: 17367.606,
 195: 17404.443,
 196: 17616.854,
 197: 17842.737,
 198: 18002.229,
 199: 18167.315}

In [133]:
array_waves = np.empty(0, dtype=float)
array_intensity = np.empty(0, dtype=float)
array_pos = np.empty(0, dtype=float)
for nb_line in lsf_data.get_line_list().keys(): 
    data = lsf_data.get_data_line(nb_line, step=10)
    pos = data['map_wave']-data['waveline']
    intensity = data['intensity']
    array_pos = np.concatenate((array_pos, pos))
    array_waves = np.concatenate((array_waves, np.full_like(pos, data['waveline'])))
    array_intensity = np.concatenate((array_intensity, intensity))
array_waves

array([14402.22 , 14402.22 , 14402.22 , ..., 18167.315, 18167.315,
       18167.315])

In [134]:
# Sort array_pos
dtype=[('pos', float), ('wave', float), ('intensity', float)]
values = [(array_pos[i], array_waves[i], array_intensity[i]) for i in range(len(array_intensity))]
tup_data = np.array(values, dtype=dtype)
tup_data = np.sort(tup_data, order=['pos', 'wave'])
array_pos = np.asarray(tup_data[:]['pos'])
array_waves = np.asarray(tup_data[:]['wave'])
array_intensity = np.asarray(tup_data[:]['intensity'])
array_waves

array([15326.48 , 17098.771, 15681.02 , ..., 14734.436, 17404.443,
       17616.854])

In [126]:
fig = plt.figure()
ax = plt.axes()
ax.plot(array_waves, array_intensity)
plt.show()

In [127]:
array_intensity, array_intensity = np.meshgrid(array_intensity, array_intensity)
array_intensity.shape

(1831, 1831)

In [128]:
interp_spline = RectBivariateSpline(array_pos, array_waves, array_intensity)

ValueError: y must be strictly increasing

In [99]:
intensities = interp_spline(array_pos, array_waves)
intensities

array([[0.00288551, 0.00288551, 0.00288551, ..., 0.00288551, 0.00288551,
        0.00288551],
       [0.00307008, 0.00307008, 0.00307008, ..., 0.00307008, 0.00307008,
        0.00307008],
       [0.00301941, 0.00301941, 0.00301941, ..., 0.00301941, 0.00301941,
        0.00301941],
       ...,
       [0.00284123, 0.00284123, 0.00284123, ..., 0.00284123, 0.00284123,
        0.00284123],
       [0.00331821, 0.00331821, 0.00331821, ..., 0.00331821, 0.00331821,
        0.00331821],
       [0.00335541, 0.00335541, 0.00335541, ..., 0.00335541, 0.00335541,
        0.00335541]])

In [100]:
fig = plt.figure()
ax = plt.axes()
c = ax.pcolormesh(array_pos, array_waves, intensities)
plt.colorbar(c, ax=ax)
plt.show()